name: chat_using_firebase_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.3.0
  firebase_storage: ^11.0.16
  loading_indicator: ^3.1.0
  
  flutter: 
    sdk: flutter
  google_sign_in: ^6.0.2
  flutter_screenutil: ^5.7.0
  get_storage: ^2.1.1
  file_picker: ^5.2.6

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

